{% set name = "pyrayt" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrayt-{{ version }}.tar.gz
  sha256: 9e7093e16466fd1d1d5cb9316313d932ddcfd3992e215ec915dbffd2df7b3350

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - matplotlib-base >=3.3.4,<4.0.0
    - numpy >=1.20.0,<2.0.0
    - pandas >=1.2.2,<2.0.0
    - python >={{ python_min }}
    - scipy >=1.6.0,<2.0.0

test:
  imports:
    - pyrayt
    - tinygfx.g3d
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rfrazier716/PyRayT
  doc_url: https://pyrayt.readthedocs.io
  summary: A toolchain for developing and simulating optical packages
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
